alert:
  ali_sms_alert: # parameters used by aliyun sms
    access_key: "MNAIrXZvcP1234Ib"
    access_secret: "ST12300HBX139NTSB1M5"
    sign_name: "test"
    template_code: "SMS_12345678"

strategy:
  simple_strategy:
    des: "13000000000" # what phone shall send sms to
    cosmos_addr: "GAIAD_ADDRRESS" # cosmos key addr to vote
    passphrase: "GAIAD_PASSWORD" # passphrase of the key
    from_key: "GAIAD_FROM" # name of the key to vote
    node: "127.0.0.1:26657" # if gaiad is not set locally, the query node should be set

scheduler:
  cron: "*/5 * * * *" # cron of scheduler, the example shows every 5 minutes
